default: &default
  api_base_uri: https://increase-transactions.herokuapp.com
  increase_token: <%= ENV['INCREASE_TOKEN'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default